spring:
  data:
    mongodb:
      database: amber
      host: localhost
      port: 27017
      username: amber
      password: amber
      authentication-database: amber
  

server:
  error:
    include-message: always
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

logging:
  level:
    org:
      keldeari:
        amber: DEBUG